First code review
opukittpcenohhr/LargePrimeNumbers pull request #1
Opened 2024-01-13 11:28 UTC by opukittpcenohhr

Initialize general project structure, implemented some factorization and primality tests

Implemented:
1. Trial Factorization
2. Pollard Pho
3. Pollard Pho-1
4. Fermat Pseudoprimality test
5. Miller-Rabin Pseudoprimality test
6. Dixon's algorithm
7. Quadratic Sieve

2024-01-18 15:19 UTC, DimaTrushin requested changes
Сделал несколько общих замечаний. Обрати внимание, я хоть и повторял замечания в похожих местах, но делал это не везде. Потому я ожидаю, что ты поправишь по аналогии во всех местах.

1) Есть большой вопрос почему у тебя часть параметров в run-time, а часть в compile-time и все это смешано в какой-то жуткой каше. Я местами сделал релеватные комментарии и предложения.
2) У тебя неконсистентная передача параметров, ты передаешь by value часто тяжелые объекты. Это плохо.
3) Еще есть проблемы с тем, что некоторые функции слишком длинные (или там 6 вложенных scope) и хочется понять, они деляться естественным образом на части или нет и почему они такие длинные, ты специально заинлайнил код потому что протестировал, что иначе работает долго?

2024-01-18 15:19 UTC, DimaTrushin commented on .clang-format
> +AllowShortLambdasOnASingleLine: Empty
Новая строчка в конце каждого файла. Эту ошибку гит сообщает всем кто клонит репозиторий. Не делай так.

2024-01-18 15:19 UTC, DimaTrushin commented on .cmake-format
А эта штука не конфликтует с clang-format? Зачем и то и другое?

2024-01-18 15:19 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS
Не делай компиляторо зависимые флаги. Или ставь проверку на компилятор перед такой установкой. Иначе ползователю с другим компилятором придется лазить по твоей системе сборке. Это плохая практика.

2024-01-18 15:19 UTC, DimaTrushin commented on src/common.h
> +typedef boost::multiprecision::cpp_int bigint;
Я бы рекомендовал привыкать к using вместо typedef, как к более современной фиче языка.

2024-01-18 15:19 UTC, DimaTrushin commented on tests/primes_data.h
> +const std::map<std::string, bool> PRIMES_DATA = {
1) Это ODR violation. Никогда не объявляй переменные в хедере. Если ты файл включишь в две единицы трансляции, то у тебя будет у линкера две глобальные переменные с одинаковым именем.
2) Если хочешь глобальный источник данных, то его надо тогда заворачивать в signleton. Желательно константный. Но может быть можно перенести в compile-time.
3) А почему не сделал compile-time map или просто std::array?
4) Еще вариант можно эти данные записать в файл, и просто читать оттуда. То есть сделать генератор исходного теста с помощью надежного метода (может быть медленного), записать в файл данные и потом просто читать их при запуске.

2024-01-18 15:19 UTC, DimaTrushin commented on tests/test_primality_tests.cpp
> +using namespace LargePrimeNumbers;
Ты в каждом тесте и так раскрываешь namespace, зачем тогда еще и глобальная команда?

2024-01-18 15:19 UTC, DimaTrushin commented on tests/test_find_factors.cpp
> +using namespace LargePrimeNumbers;
У тебя не консистентно. Ты в другом тесте раскрываешь namespace локально в каждом тесте, а тут глобально.

2024-01-18 15:19 UTC, DimaTrushin commented on tests/test_factor_base.cpp
> +const std::vector<int> EXPECTED_FACTOR_BASES = {2,  3,  5,  7,  17,
Почему не constexpr std::array?

2024-01-18 15:19 UTC, DimaTrushin commented on tests/test_factor_base.cpp
> +using namespace LargePrimeNumbers;
Опять неконсистентность.

2024-01-18 15:19 UTC, DimaTrushin commented on src/logging.h
> +#define ERROR() BOOST_LOG_TRIVIAL(error)
define-ы внутри namespace не имеют смысла. Они всегда глобальные. Вопрос почему ты не определяешь функции в своем namespace, которые уже дергают эти макросы? Никогда не пиши дефайны в пространстве имен, чтобы не смущать читателя.

2024-01-18 15:19 UTC, DimaTrushin commented on src/legendre_symbol.h
> +int find_legendre_symbol(bigint n, int p);
1) Почему принимаешь bigint не по константной ссылке? Это потенциально дорого.
2) А почему второй аргумент обязательно int? Даже не long long?

2024-01-18 15:19 UTC, DimaTrushin commented on src/fermat_pseudoprimarity_test.h
> +bool is_fermat_pseudoprime(bigint n) {
Почему by value?

2024-01-18 15:19 UTC, DimaTrushin commented on src/fermat_pseudoprimarity_test.h
> +      // We know, that either base == n or n is not prime
Минутка обсуждения дизайна. На сколько я понимаю тест Ферма имеет два параметра n и p (ты передаешь целую пачку p через шаблон). Но по замыслу теста можно считать, что взаимная простота n и p это precondition для теста. Вообще у зависимых тестов можно определить две версии: сырую, которая считает, что все проверки до него другими тестами выполнили и она считает это все как precondition и выполняет только свою часть. И комплексную часть, которая сначала вызывает все другие тесты, а потом уже вызывает свою часть.

2024-01-18 15:19 UTC, DimaTrushin commented on src/fermat_pseudoprimarity_test.h
> +template <FermatPseudoprimalityParams params>
А почему параметры передаются в compile-time, а не в run-time? В чем содержательный смысл? Ты просто руки себе связываешь тем, что часть параметров надо передавать в run-time, а часть в compile-time. Это потенциально сделает работу кода неудобной. Какая мысль за таким разделением?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +T addmod(const T& a, const T& b, const T& mod) {
Такой вопрос. А нет смысла делать inplace операции по типу +=? Там не получается сделать какую-то оптимизацию на том, что можно переиспользовать память?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +inline int addmod<int>(const int& x, const int& y, const int& p) {
1) Плохая тема принимать int by reference. И вообще возникает вопрос: Нахуя, а главное зачем эта специализация? Почему не подходит общий код?
2) По хорошему я бы тут сделал класс хелпер, который бы вычислял как принимать тип по ссылке или по значению и вызывал бы тут. Например
```cpp
template<class T>
using ArgAs = std::conditional<std::is_arithmetic_v<T>, T, const T&>;
```
И потом использовать ArgAs<T> в аргументах. Правда частичная специализация функций не разрешена, потому придется завернуть функцию внутрь шаблона структуры как статическую.

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +T powmod(T a, T b, const T& mod) {
1) Не уверен, что хорошая идея принимать by value. Ты не всегда запускаешь цикл внизу.
2) Что если b <= 0? Так и предполагается, что ответ будет 1?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +T gcd(const T& a, const T& b) {
А чем std::gcd не подходит? Он не со всеми типами работает?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +  if (a >= 0) {
А не хочешь написать что-то вроде
```cpp
return a * (a > 0) - a * (a < 0);
```
?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +  if (g != 1 && g != n) {
А не надо ли тебе оборачивать константы T(1)?

2024-01-18 15:19 UTC, DimaTrushin commented on src/utility.h
> +  if (g != 1 && g != n) {
А что если знаки какие-нибудь есть у n и factor?

2024-01-18 15:19 UTC, DimaTrushin commented on src/trial_primality_test.cpp
> +  for (bigint i = 2; i * i <= x; i++) {
1) Здесь можно проверить делимость на 2 вне цикла, а потом встать в 3 и идти i += 2 (с шагом 2) только по нечетным. Это в 2 раза снижает количество операций.
2) И еще мне всегда было интересно потестить разницу. Что быстрее. Один раз заранее посчитать корень с округлением и сравнивать i <= sqrt или вот так вот каждый раз считать квадрат. Нет желания потестить?

2024-01-18 15:19 UTC, DimaTrushin commented on src/trial_primality_test.cpp
> +bool is_prime_trial(bigint x) {
by value?

2024-01-18 15:19 UTC, DimaTrushin commented on src/trial_find_factor.h
> +std::optional<bigint> find_factor_trial(bigint n);
Выглядит так, что is_prime_trial можно реализовать через эту функцию.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +inline bigint get_polynomial_value(const bigint& r, const bigint& n) {
Странное название функции, ты вроде просто r^2 mod n считаешь, а называется она polynomial_value. Чего я не понимаю?

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +    const bigint& r, const bigint& n, std::vector<int>& factorization_powers,
Плохо использовать сырые типы вроде std::vector<int>. Ты можешь захотеть потом другой контейнер использовать или еще какие внести изменения. Это для типов как магические константы. Тут возникает вопрос где вводить эти псевдонимы. И вот для этого уже удобно паковать функции и псевдонимы внутри структуры или класса.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +                                        std::vector<int> factor_base) {
Почему by value? Это может быть дорого. Если хочешь переиспользовать память можешь по rvalue ссылке передавать.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +  constexpr size_t FILL_FACTOR = 3;
Не используй такие имена для констант. Такие имена обычно используются для макросов. Это будет сбивать с толку людей. Обычно используют префикс kContant или k_constant для констант. Но ты можешь любой стиль использовать.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +           (1 + FILL_FACTOR) * factor_base_size + 1>
А не хочешь завести нормальные constexpr имена для этих выражений?

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +std::optional<bigint> find_factor_dixon(bigint n,
Такой вопрос. Алгоритм Диксона разбивается на какие-то разумные подфункции или нет? А то выглядит очень длинно. Я понимаю, что математические алгоритмы редко можно как-то записать хорошо, но тем не менее хочется понять есть ли тут такая возможность. Пока твой код выглядит так, что тут на самом деле есть высокоуровневые шаги, которые ты просто явно вставил друг за другом.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  }
А тебе точно нужны именно такие операции? Оставь только один способ обращаться к индексам, например через оператор (i, j).

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  std::vector<std::bitset<M>> a;
1) Почему не std::array<std::bitset<M>, N> a;? А то у тебя битсет это compile-time размера массив, а хранишь ты их в run-time объекте, который инициализируешь compile-time параметром. Если хочешь сделать дешовым move, то нужно обернуть еще в std::unique_ptr.
2) Плохое имя переменной. Во-первых, однобуквенное имя не информативно. Во-вторых, переменные класса являются глобальными данными для методов класса. Потому нужен механизм отличать их от локальных переменных методов класса. Например добавляют _ в конце имени.
3) Еще как вариант можно использовать std::vector<bool>. Этот класс имеет сжатие данных специально для класса bool. У тебя будет тратиться по одному биту на элемент. И просто использовать умную нумерацию внутри оператора доступа.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  F2Matrix() : a(N) {}
Вместо этого лучше придай a дефолтное значение при объявлении, а тут напиши F2Matrix() = default;

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  const bool& operator()(size_t i, size_t j) const {
Есть правило. Все базовые типы передются by value (так же легкие объекты нужно передавать by value). А вот уже тяжелые классы по константной ссылке. Не понимаю зачем тебе тут константная ссылка.

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +template <size_t N, size_t M>
А почему параметры в compile-time?

2024-01-18 15:19 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +        if (matrix[row_under][i]) {
6 вложенных scope! Даже в ядре Linux запрещено делать больше 3.

2024-01-18 15:19 UTC, DimaTrushin commented on src/pollard_rho_find_factor.h
> +  const std::array<BasesType, start_values_count> start_values;
Если константы, то почему не constexpr?? Нет смысла делать константные поля в структурах.

2024-01-18 15:19 UTC, DimaTrushin commented on src/pollard_rho_find_factor.h
> +  auto f = [&n](bigint x) {
плохое имя

2024-01-18 15:19 UTC, DimaTrushin commented on src/pollard_rho_find_factor.h
> +    for (size_t i = 0; i < params.max_iterations; i++) {
Обычно вложенные циклы -- это ошибка дизайна. Чаще всего ты либо не использовал стандартный алгоритм либо не выделил подфункцию.

2024-01-18 15:19 UTC, DimaTrushin commented on src/pollard_rho_find_factor.h
> +              << " current_gcd: " << current_gcd;
Кстати, а этот код в релизе тоже остается?

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/find_congruence.cpp
> +  std::mt19937 rng(239);
А ничего, что у тебя рандома нет? У тебя при каждом запуске генератор создается заново. То есть между вызовами не будет никакой разницы. Не хочешь сделать статическим генератор? Или вообще завернуть его в какой-нибудь класс class Random и внутри него делать всю нужную инициализацию и тебе предоставлять тут нужный интерфейс?

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/find_congruence.cpp
> +    int candidate = static_cast<int>(rng());
1) явные касты в коде -- ошибка дизайна. Касты не должны вызываться в бизнес логике. Они лишь должны вызываться в методах объектов, которые отвечают за эту конвертацию при доступе.
2) Почему ты используешь генератор явно, а не используешь распределение порожденное генератором?

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/find_congruence.cpp
> +  auto v = find_v((p + 1) / 2, p, h, n_residue_modulo_p, h,
Что этот метод делает? Мне не нравится название. Тут есть что-то разумное?

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_base.cpp
> +  for (int i = 2; i <= static_cast<int>(max_number_to_check); i++) {
Убрать касты.

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_base.cpp
> +  std::vector<bool> is_prime(max_number_to_check + 1, true);
Ты бежишь по всем числам или только по нечетным?

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/quadratic_sieve.h
> +struct QuadraticSieveParams {
Вместо структуры с константыми полями сделай константную структуру с неконстантными полями. Ну либо сделай constexpr static поля, если хочешь compile-time константы.

2024-01-18 15:19 UTC, DimaTrushin commented on src/quadratic_sieve/quadratic_sieve.h
> +std::optional<bigint> find_factor_quadratic_sieve(bigint n) {
Можно ли отрефакторить метод?

2024-01-21 09:41 UTC, opukittpcenohhr commented on .cmake-format
Это чисто CMakeLists форматировать, так что все ок

2024-01-21 09:42 UTC, opukittpcenohhr commented on tests/primes_data.h
> +const std::map<std::string, bool> PRIMES_DATA = {
Сделал функию-геттер, данные для которой хранятся в приватном неймспейсе в .cpp

2024-01-21 09:42 UTC, opukittpcenohhr commented on tests/test_factor_base.cpp
> +const std::vector<int> EXPECTED_FACTOR_BASES = {2,  3,  5,  7,  17,
Починилось когда поменял дизайн тестов

2024-01-21 09:43 UTC, opukittpcenohhr commented on src/logging.h
> +#define ERROR() BOOST_LOG_TRIVIAL(error)
Просто удалил этот файл -- так проще

2024-01-21 09:43 UTC, opukittpcenohhr commented on src/legendre_symbol.h
> +int find_legendre_symbol(bigint n, int p);
1. Починил везде
2. Нет причины, стал принмать bigint

2024-01-21 09:44 UTC, opukittpcenohhr commented on src/fermat_pseudoprimarity_test.h
> +      // We know, that either base == n or n is not prime
Сделал так, постарался в комментариях перечислить все precondition-ы

Будет полезно еще и для бенчмарков

2024-01-21 09:45 UTC, opukittpcenohhr commented on src/utility.h
> +T addmod(const T& a, const T& b, const T& mod) {
Думаю что кейс a = addmod(a, a, x) компилятор сам справится оптимизировать

2024-01-21 09:46 UTC, opukittpcenohhr commented on src/utility.h
> +inline int addmod<int>(const int& x, const int& y, const int& p) {
Убрал специализацию, второй вопрос решился сам собой

2024-01-21 09:46 UTC, opukittpcenohhr commented on src/utility.h
> +T powmod(T a, T b, const T& mod) {
2. Сделал assert

2024-01-21 09:46 UTC, opukittpcenohhr commented on src/utility.h
> +T gcd(const T& a, const T& b) {
Да, с cpp_int не работает

2024-01-21 09:46 UTC, opukittpcenohhr commented on src/utility.h
> +  if (g != 1 && g != n) {
сделал assert

2024-01-21 09:47 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.h
> +    const bigint& r, const bigint& n, std::vector<int>& factorization_powers,
Это на самом деле внутренняя функция-хелпер, унес ее в .cpp

2024-01-21 09:48 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.h
> +           (1 + FILL_FACTOR) * factor_base_size + 1>
Уже не consexpr, так что неактуально

2024-01-21 09:48 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.h
> +std::optional<bigint> find_factor_dixon(bigint n,
Согласен, разбил

2024-01-21 09:48 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +  }
Нужны, потому что делаю xor= для двух рядов

2024-01-21 09:49 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +  std::vector<std::bitset<M>> a;
Использовал boost:dynamic_bitset, потому что очень важно делать xor= двух рядов за N / 64

Протестил vector<bool>, было плохо

2024-01-21 09:49 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +        if (matrix[row_under][i]) {
Постарался сделать лучше

2024-01-21 09:50 UTC, opukittpcenohhr commented on src/pollard_rho_find_factor.h
> +              << " current_gcd: " << current_gcd;
Нет, если стоит правильный log_level то он не вычисляется даже

2024-01-21 09:50 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_congruence.cpp
> +  std::mt19937 rng(239);
1. Вынес класс в random.h
2. У тебя при каждом запуске генератор создается заново -- меня устраивает такое поведение

2024-01-21 09:51 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_congruence.cpp
> +  auto v = find_v((p + 1) / 2, p, h, n_residue_modulo_p, h,
Добавил комментарий

2024-01-21 09:51 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_factor_base.cpp
> +  std::vector<bool> is_prime(max_number_to_check + 1, true);
Стал только по нечетным бежать

2024-01-21 09:51 UTC, opukittpcenohhr commented on src/quadratic_sieve/quadratic_sieve.h
> +std::optional<bigint> find_factor_quadratic_sieve(bigint n) {
Постарался вынести все шаги

2024-01-21 10:43 UTC, opukittpcenohhr commented
Самые глобальные изменения
1. Стал принимать везде bigint и по const-ссылке
2. Сделал все аргументы runtime
3. Лучше разбил код на логические части, добавил два интерфейса методам

В остальном по сути просто исправил все твои комменты

2024-03-26 17:54 UTC, DimaTrushin requested changes
Выглядит очень хорошо. Есть местами косяки с дизайном, но их очень легко уловить, потому что написано очень толково и структурировано.
Помню, что хотел много чего тут написать, но пока сделал комментарии и добрался до конца уже все забыл. В любом случае все эти замечания указаны в комментариях к ревью. Там были какие-то мелочи вроде работы с именами.
Еще если какие-то замечания по 4 вложенным scope разумно не исправляются и делают код хуже, то не стоит переделывать. А остальные комментарии более или менее понятны.

2024-03-26 17:54 UTC, DimaTrushin commented on .clang-format
> +AlignAfterOpenBracket: AlwaysBreak
Скажем нет новым строчкам в конце файла! =)

2024-03-26 17:54 UTC, DimaTrushin commented on .cspell.json
>  }
Ну камон!

2024-03-26 17:54 UTC, DimaTrushin commented on CMakeLists.txt
> +  message(FATAL_ERROR "You can use only Clang compiler")
Спасибо тебе за такую замечательную кросплатформенность... Спасибо, что жесткий блок только на mac не поставил.

2024-03-26 17:54 UTC, DimaTrushin commented on tests/data.h
Как вариант еще можно из файла читать данные. А в файл можно их сгенерировать медленным надежным методом. Например все простые которые в uint32_t влазят найти и записать в файл. А потом с помощью этих данных проверять. Хранить можно std::vector<bool> так, что vec[i] является true тогда и только тогда, когда 2 *i + 3 является простым. Ну и хранить можешь в бинарном виде, тогда оно еще и супер эффективно будет.

2024-03-26 17:54 UTC, DimaTrushin commented on src/random.h
> +class RandomBigintGenerator {
Убери слово Generator, оно тут лишнее, получается слишком длинное имя класса.

2024-03-26 17:54 UTC, DimaTrushin commented on src/random.h
> +  bigint generate_uniform_random(const bigint& min, const bigint& max) {
Убери слово random в названии. Ты просто подумай, как у тебя класс будет использоваться. Ты и так знаешь, что это класс для рандома, теперь тебе лишь надо в имени метода знать какое распределение ты используешь. Думаю, что даже от generate можно избавиться в пользу более короткого слова.

2024-03-26 17:54 UTC, DimaTrushin commented on src/random.h
> +  RandomBigintGenerator(int seed) : mt_(seed) {}
А там точно int сид в boost::mt19937?

2024-03-26 17:54 UTC, DimaTrushin commented on src/random.h
> +  RandomBigintGenerator(int seed) : mt_(seed) {}
Класс не шаблонный, почему имплементация не вынесена в cpp файл?

2024-03-26 17:54 UTC, DimaTrushin commented on benchmarks/plot_stats_by_bases_count.cpp
> +};
1) Все что объявляется в cpp файле должно быть завернуто в anonymous namespace включая концепты!
2) Почему func перехватывается по T, а не по T&&? Почему const int?
3) Почему это не глобальный concept?

2024-03-26 17:54 UTC, DimaTrushin commented on benchmarks/plot_stats_by_bases_count.cpp
> +void plot_detected_pseudoprimes_vs_bases_count_for_pseudoprimality_test(
Тоже заверни в anonymous nanespace

2024-03-26 17:54 UTC, DimaTrushin commented on benchmarks/plot_stats_by_bases_count.cpp
> +  for (auto log_range_begin : log_ranges_begin) {
Максимально плохие названия. Я час искал 10 отличий.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.h
> +  size_t factor_base_size;
А какой смысл делать такую структуру с одним полем? Ты пытаешься избежать каста из CfracParams в size_t? Или каста в обратную сторону? Или хочешь что-то еще сюда добавить в будущем?

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.h
> +    const bigint& n, const CfracParams& params);
такую легкую структуру как параметры можно и by value передавать. Но это не так важно.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.h
> +struct CfracParams {
Что это вообще значит? Что за название?

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +  // If n is a perfect square, Bhascara-Brounker sequence is not defined
Это пример хорошего комментария

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +                          << factor_base.back()
А всегда не пусто это множество?

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +  DixonsAlgorithm dixons_algorithm(n, factor_base);
Я бы ожидал std::move(factor_base). Ты больше нигде не используешь это множество. Просто тут ты делаешь лишнюю копию.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +      get_initial_brounker_sequence_items(n, sqrt_n);
Вот это выглядит как кишки итератора. То есть я бы ожидал либо итератор в смысле iterable, который инициализируется первым объектом и потом умеет сдвигаться. Либо прокси объект, который симулирует контейнер и имеет методы begin, end.
Ну и итератор может быть по парам объектов или что-то в этом духе, тут уже имплементировать можно по-разному.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +        current_item, previous_item, n, sqrt_n);
Вот тут можно было бы сделать
```cpp
auto new_item = *iterator;
// code
++iterator;
```
И вся логика содержится внутри итератора и не надо передавать явно n и sqrt_n в него. И раз его перемещение зависит от знания двух итераторов сразу, значит два итератора внутри должны быть. Ну в общем все это детали, которые тут нас не интересуют.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +    total_candidates++;
Если этот флаг показывает количество итераций, то можно у итератора сделать метод возвращающий сколько раз был вызван ++ на нем. Но может быть это идейно тут не правильно, если ты считаешь разные величины.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +      if (factored_candidates % 100 == 0) {
На будущее хорошо бы подумать, как этот параметр сюда передавать. Потому что мало ли и это число будет слишком большим или слишком маленьким.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +  return dixons_algorithm.find_factor();
found_factors

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/find_factor_cfrac.cpp
> +                          << (double)factored_candidates /
Лучше не используй си-касты. На крайняк пиши double(...), это хотя бы синтаксически на плюсы похоже. А так тут приходится явно говорить про static_cast<double> и при этом достаточно только один из аргументов кастануть.

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/bhascara_brounker_sequence.h
> +
Можно поступить одним из двух способов. Либо сделать iterable, либо прокси контейнер. Первое делается так
```cpp
struct BhascaraBrounker {
  struct Item {
    bigint a;
    bigint b;
    bigint c;
    bigint p;
  };
  class Iterable {
  public:
    const Item& operator*() const;
    const Item* operator->() const;
    Iterable& operator++();
    bool isComplete() const;
  private:
    Item current_;
    Item previous_;
    bigint n_;
    bigint sqrt_n_;
  };
  static Iterable create(const bigint& n);
  static Iterable create(const bigint& n, const Bigint& sqrt_n);
};
```
И тогда ты можешь итерироваться как хочешь в цикле вида
```cpp
auto iter = BhascaraBrounker::create(n);
while (!iter.isComplete()) {
  // use *iter;
  ++iter;
}
```
Если хочешь второе, то надо сделать то же самое, но еще делается прокси контейнер
```cpp
struct BhascaraBrounker {
  struct Item {
    bigint a;
    bigint b;
    bigint c;
    bigint p;
  };
  class Iterator {
  public:
    const Item& operator*() const;
    const Item* operator->() const;
    Iterable& operator++();
    friend bool operator==(const Iterator& lhs, const Iterator& rhs);
    friend bool operator!=(const Iterator& lhs, const Iterator& rhs);
  private:
    Item current_;
    Item previous_;
    bigint n_;
    bigint sqrt_n_;
  };
  class Sequence {
  public:
    using const_iterator = Iterator;
    const_iterator begin() const;
    const_iterator end() const;
  private:
    bigint n_;
    bigint sqrt_n_;
  };

  static Sequence makeSequence(const bigint& n);
  static Sequence makeSequence(const bigint& n, const bigint& sqrt_n);
};
```
И тогда ты можешь этим пользоваться как в stl
```cpp
auto sequence = BhascaraBrounker::makeSequence(n);
for(const auto& item : sequence) {
  // используешь item как элемент типа BhascaraBrounker::Item.
}
```

2024-03-26 17:54 UTC, DimaTrushin commented on src/cfrac/bhascara_brounker_sequence.h
Очень хорошая идея, я просто хочу ее из языка Си переделать в язык C++. Ну и помочь сократить названия.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  std::vector<boost::dynamic_bitset<>> a_;
Плохая идея делать вектор векторов (что по сути у тебя здесь сделано, потому что dynamic_bitset это std::vector со сжатием до 8 элементов на один байт). Лучше уж сделать dynamic_bitset размера m * n и хранить один из размеров. А потом уже сделать умную адресацию типа operator(i, j) возвращает a_[i * m + j] или i * n + j. Ну и назвать rows и columns вместо m и n. Это сильно повышает производительность. Потому что машине проще посчитать новый индекс, чем прогружать из памяти новую порцию из другой ячейки вектора.

UPD. Я посмотрел твою имплементацию. Да, надо тестить какой подход лучше. Тут сейчас не очевидно. Но так как минимум проще.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +  F2Matrix(size_t row_count, size_t column_count)
Почему имплементация в хедере если класс не шаблонный?

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +void perform_gaussian_elimination(F2Matrix& matrix, size_t columns_to_perform);
Лучше выходные параметры (то есть те данные которые ты хочешь менять) сообщать последними. И лучше их передавать по указателю. Потому что обрати внимание, как ты будешь вызывать метод
```cpp
perform_gaussian_elimination(matrix, 5);
// против
perform_gaussian_elimination(5, &matrix);
```
Во втором случае так как matrix передается по указателю, то код подсказывает программисту, что ты собираешься менять matrix.
И в целом принято делать так. Входные параметры идут до выходных. Входные передаются либо by value либо by const reference. Выходные передаются по указателю. Это обще принятые стандарты в Си. В плюсах этот подхъод тоже используют. Исключением являются операторы operator>>, где принято аргументы передавать по ссылке и приходится так делать, потому что это часть синтаксиса.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.h
> +void perform_gaussian_elimination(F2Matrix& matrix, size_t columns_to_perform);
Не совсем понятно название, ты хочешь привести к улучшенному ступенчатому виду над Z_2? Если да, то почему не reduce_to_row_echelon_form? Так понятно, что ты не просто что-то делаешь гауссом, а понятно какой результат у оператции.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.cpp
> +      std::swap(matrix[i], matrix[pivot]);
Ты все таки пользуешься возможностью вытащить строку и быстро поменять две строки местами. Но мне кажется стоит побенчмаркать подход с единым контейнером и посмотреть на сколько это будет лучше работать (или хуже).

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/f2_matrix.cpp
> +    assert(matrix[i][i] == 1);
Это странно, у тебя что все главные переменные будут только на диагонали обязательно? Или я чего-то не понимаю?

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +        factorized_candidates_{},
Дефолтные конструкторы можно не звать. Они сами вызовутся.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +  explicit DixonsAlgorithm(
Нет смысла в слове explicit на конструкторе, который нельзя позвать с одним аргументом. Его лучше убрать.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +      const bigint& n, const std::vector<size_t>& factor_base,
Глобально плохая идея принимать конкретные контейнеры в качестве аргументов.
1) Для начала потому что ты можешь написать так
```cpp
DixonsAlgorithm alg(4, {1, 2, 3});
```
В этом случае {1, 2, 3} имеет тип std::initializer_list<int>, что не совпадает с std::vector<size_t>. Потому компилятор в этом месте сделает каст и создаст временный объект типа std::vector<size_t> и в него скопирует содержимое std::initializer_list<int>. После чего ты в своем констукторе пишешь factor_base_(factor_base) где вызывается copy constructor и ты еще раз копируешь временный объект, который потом разрушается после вызова конструктора. В моем примере это маленькие контейнеры, но надо понимать. что копирование контейнеров -- это всегда плохо.
2) Обычно если ты принимаешь конкретный контейнер, то это какой-то приватный конструктор (но не обязательно). Но в любом случае лучше принимать по rvalue reference чтобы можно было украсть кишки
```cpp
DixonsAlgorithm(const bigint& n, std::vector<size_t>&& factor_base, int fill_factor = 1)
  : n_(n),
    factor_base_(std::move(factor_base), ...
```
Тогда ты всегда будешь мувать эту фактор базу внутрь. Если ты хочешь чтобы оно работало и с lvalue аргументами, то стоит оставить и такой конструктор.
Еще как вариант, чтобы не писать два конструктора, можно принимать by value и всегда мувать
```cpp
DixonsAlgorithm(const bigint& n, std::vector<size_t> factor_base, int fill_factor = 1)
  : n_(n),
    factor_base_(std::move(factor_base), ...
```
Это стоит на 1 мув дороже, чем вариант со ссылками. Но в случае вектора мув -- это три указателя, а ссылка -- один указатель. Разница не большая и скорее всего вообще не заметная (разница технически может быть если у тебя количество аргументов в районе 4, там есть ситуации на 64 битных машинах когда аргументы могут сразу в регистры складываться, а не на стек, но я не знаю наизусть этих стандартов и не знаю на сколько в этом случае это повлияет).
3) Если ты хочешь в любом случае копировать принимаемые данные и не хочешь вовровать внутренности, то либо принимают std::initializer_list<size_t> либо принимают итераторы. Но если пользоваться итераторами, то это ломает api, точнее делает его другим, так что можно принимать просто initializer_list. Ну либо можно std::span принимать и уже смотреть по нему, можно из него мувнуть или нельзя.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +  std::optional<bigint> check_factor_candidate(size_t i) const;
Не нравится название. Это не совсем check, это get_if_possible или что-то в этом духе или get_if_acceptable надо подумать над названием.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.h
> +  void process_candidates(std::span<const bigint> candidates);
Я не очень понимаю, что этот метод делает. Он просто проверяет являются ли числа из заданного ренджа делителями? Или что? Если да, то почему это такой сложный алгоритм требующий каких-то дополнительных данных, буфферов и прочего. Если нет, то тут явно подразумевается, что на этих кандидатов должны выполняться какие-то пререквизиты. Но тогда вопрос, а кто должен строить эти данные с такими пререквизитами? Как алгоритм должен отрабатывать, если это не выполняется? Почему это не часть алгоритма строить такие данные? Или алгоритм диксона предполагает, что кандидатов можно строить разными методами? Если да, то почему не сделать это параметром алгоритма и не хранить этот метод внутри std::function или другого стирающего типа? Просто от алгоритма факторизации я ожидаю какой-то такой дизайн
```cpp
DixonsAlgorithm algo(/*params*/);
bigint n1 = /*init*/;
auto factors1 = algo.factorize(n1);
bigint n2 = /*init*/;
auto factors2 = algo.factorize(n2);
```
А тут какие-то странные методы по обработке кандидатов. Я не понимаю до конца логику происходящего.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +bigint DixonsAlgorithm::perform_polynomial_factorization_over_factor_base(
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +      factorization_powers_cache_.begin(), factorization_powers_cache_.end(),
Заведи метод reset_cache, иначе это нарушение уровня абстракции.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +bool DixonsAlgorithm::factorize_over_factor_base_and_fill_powers_matrix(
Зачем тебе функция с двумя глаголами, которая делает две вещи? Так как это приватный метод и заполнять матрицу степеней имеет смысл только после вызова факторизации, то ты можешь это гарантировать просто написав методы класса правильно. Пользователь же не будет дергать эти методы. Просто передавай результат полиномиальной факторизации в метод заполнения матрицы и все.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +        auto g_r = mulmod<bigint>(
4 вложеных scope даже в ядре Linux запрещено больше 3.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +    if (auto factor = check_factor_candidate(i)) {
Плохое название метода. Из названия не ясно, что он возвращает. Ну и написано так, что надо еще додуматься, что это optional проверяется на непустоту.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +  perform_gaussian_elimination(matrix_, factor_base_.size());
Не понятно, какую роль играет второй аргумент. И не видно, что matrix_ меняется.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +  }
Я бы тут ожидал как минимум чтение результата от метода process_candidate и если false, то делал return. Иначе как-то странно, что process_candidate у тебя после какого-то количества вызовов ничего не обрабатывает, а process_candidates обрабатывает. Методы работают совершенно по разному и снаружи это совсем не ясно, почему process_candidate(5) ничего не делает, а process_candidates({5}) отрабатывает.

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +    x = boost::multiprecision::sqrt(x);
А в какую сторону тут округляется корень? С этим проблем нет?

2024-03-26 17:54 UTC, DimaTrushin commented on src/dixons_algorithm/dixons_algorithm.cpp
> +  bool is_complete_square = true;
Мне глобально не нравится наличие флагов в методах. Обычно это означает, что ты не создал вспомогательную функцию, которая должна была вернуть значение флага через return и ты его просто хотел проверить в if-е, а не складывать в вспомогательную переменную.

2024-03-26 17:54 UTC, DimaTrushin commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.h
> +bool is_fermat_pseudoprime_relative_to_base(const bigint& n, int base);
Я на всякий случай уточню, что результат бинарный. То есть нет смысла вводить статус с несколькими состояниями типа: простой, не простой, подозрение на простоту, подозрение на непростоту?

2024-03-26 17:54 UTC, DimaTrushin commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.h
> +bool is_fermat_pseudoprime_relative_to_base(const bigint& n, int base);
Чтобы сократить названия, можно сделать
```cpp
struct Fermat {
  static bool is_pseudoprime_wrt(const bigint& n, int base); // wrt = with respect to
};
```
И тогда можно звать метод
```cpp
Fermat::is_pseudoprime_wrt(n, 13);
```
И если у тебя есть другие тесты, то в них методы можно называть одинаково. И можно делать тестирующие функции шаблонными, типо
```cpp
template<class Test>
struct CheckCorrectness {
  static bool is_correct();
};
// и звать потом так
bool result = CheckCorrectness<Fermat>::is_correct();
```
Это так для идей как структурировать код.

2024-03-26 17:54 UTC, DimaTrushin commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.cpp
> +    // for all relatively prime bases, and this is not the case
Очень правильно что добавил тут комментарий, иначе я бы голову сломал, почему тут написано именно так. Тем не менее, хочу порассуждать на эту тему. Ведь в конечном итоге, нам же важно понять простое число или составное. Если же gcd дало нетривиальный делитель для n, не хотим ли мы вернуть результат, который бы говорил, что число составное? Может быть не возвращать true или false, а завести enum class Status {Prime, Composite, PseudoPrime};? То есть мы либо убеждаемся, что оно составное, либо убеждаемся, что нашли делитель, либо убеждаемся, что все тесты пройдены и оно псевдопростое?

2024-03-26 17:54 UTC, DimaTrushin commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.cpp
> +  auto predicate_value = powmod<bigint>(base, n - 1, n);
А не надо ли добавить метод, который сначала делает проверку на взаимную простоту n и base и уже потом вызывает этот метод?

2024-03-26 17:54 UTC, DimaTrushin commented on src/legendre_symbol/legendre_symbol.cpp
> +int find_legendre_symbol(const bigint& n, const bigint& p) {
А бустовская длинка его не умеет считать?

2024-03-26 17:54 UTC, DimaTrushin commented on src/legendre_symbol/legendre_symbol.cpp
> +  assert(p % 2 == 1);
Не хочешь jacobi symbol еще добавить? Он помогает считать символ лежандра и определен всегда.

2024-03-26 17:54 UTC, DimaTrushin commented on src/legendre_symbol/legendre_symbol.cpp
> +  }
это можно сократить до 
```cpp
return 2 * (pow == 1) - 1;
```
Не знаю, на сколько это стоит делать правда. Но так, наблюдение по сокращению количества строчек кода.

2024-03-26 17:54 UTC, DimaTrushin commented on src/pollard_rho/pollard_rho_find_factor.cpp
> +    second_pointer = next_value(next_value(second_pointer));
Не хочешь это тоже завернуть в итератор? Но в целом и так выглядит хорошо.

UPD Я только потом понял, что тут что-то странное происходит. Один указаель сдвигается один раз, в другой два раза. Хм...

2024-03-26 17:54 UTC, DimaTrushin commented on src/pollard_rho/pollard_rho_find_factor.h
> +// n is known composite
То есть мы должны заранее знать, что оно составное?

2024-03-26 17:54 UTC, DimaTrushin commented on src/quadratic_sieve/find_congruence.h
> +std::vector<bigint> find_all_congruences(const bigint& n, const bigint& p);
То есть это работает не только когда p простое и может быть больше 2 ответов?

UPD оказалось что ты возвращаешь не более двух. Тогда вектор кажется плохим вариантом для ответа. Но даже не знаю, что тут предложить.

2024-03-26 17:54 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_base.cpp
> +  std::vector<size_t> result{2};
Это создает вектор с одним элементом 2. Это так и запланировано или тут хотелось вектор размера 2? Почему 2 складывается до reserve? Из-за этого у тебя 2 аллокации вместо 1. Я бы сконструировал пустой вектор, потом бы сделал reserve и потом бы сделал push_back(2).

2024-03-26 17:54 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_base.cpp
> +  // 1 -- so in our case 100 is sufficient for factors_count <= 10^6 for sure
Не надо ли на это ассерт поставить, чтобы можно было отловить, если мы это условие нарушили?

2024-03-26 17:54 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_base.cpp
> +    if (is_prime[i]) {
Лучше сделать еще хитрее. Можно хранить в 2 раза меньше элементов, если считать, что в is_prime[i] лежит результат для 2 * i + 3. Тогда ты еще и не будешь хранить четные элементы. Только 2 надо будет до этого заранее проверить.

2024-03-26 17:54 UTC, DimaTrushin commented on src/quadratic_sieve/find_factor_quadratic_sieve.h
> +    const bigint& n, const std::vector<size_t>& factor_base,
А почему ты где-то используешь span, а где-то vector? Просто забыл переписать все на span?

2024-03-26 17:54 UTC, DimaTrushin commented on src/strong_pseudoprimality/strong_pseudoprimality_test.cpp
> +std::pair<size_t, bigint> find_highest_power(bigint n, const bigint& k) {
назови find_highest_power_of
И еще возвращай не пару, а struct с полями degree и factor. Будет лучше, чем first и second,

2024-03-26 17:54 UTC, DimaTrushin commented on src/strong_pseudoprimality/strong_pseudoprimality_test.cpp
> +bool is_strong_pseudoprime(const bigint& n, std::span<const int> bases) {
Любопытно, что где-о у тебя span<int>, а где-то span<const int>.

2024-03-26 17:54 UTC, DimaTrushin commented on src/trial_find_factor.cpp
> +  if (n % 2 == 0 && n > 2) {
А тебя не смущают отрицательные значения?

2024-03-26 17:54 UTC, DimaTrushin commented on src/trial_primality_test.h
> +bool is_prime_trial(const bigint& x);
А почему эту функцию нельзя было поместить водин хедер с методом, который она зовет? по поиску множителя?

2024-03-26 17:54 UTC, DimaTrushin commented on src/utility.h
> +T powmod(T a, T b, const T& mod) {
Надо еще все precondition прописать у методов.

2024-03-29 10:53 UTC, opukittpcenohhr commented on tests/data.h
Понимаю, но думаю что для текущей ситуации подходит то что уже есть -- у меня нет проблем с местом сейчас, а по коду такой метод самый простой

2024-03-29 15:43 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_factor_base.cpp
> +  // 1 -- so in our case 100 is sufficient for factors_count <= 10^6 for sure
Да, уже есть чуть ниже по коду

2024-03-29 16:58 UTC, opukittpcenohhr commented on .clang-format
> +AlignAfterOpenBracket: AlwaysBreak
fixed)

2024-03-29 16:58 UTC, opukittpcenohhr commented on .cspell.json
>  }
К сожалению так надо делать, но имхо плюсов больше чем минусов

2024-03-29 16:58 UTC, opukittpcenohhr commented on CMakeLists.txt
> +  message(FATAL_ERROR "You can use only Clang compiler")
Хз почему вообще добавил, убрал

2024-03-29 16:59 UTC, opukittpcenohhr commented on src/random.h
> +  RandomBigintGenerator(int seed) : mt_(seed) {}
Принял в unit32, как у mt

2024-03-29 17:00 UTC, opukittpcenohhr commented on benchmarks/plot_stats_by_bases_count.cpp
> +  for (auto log_range_begin : log_ranges_begin) {
Добавил префикс single_

2024-03-29 17:00 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.h
> +  size_t factor_base_size;
Да, не хочу касты туда-сюда

+а будущем добавлю сюда что-то возможно

2024-03-29 17:00 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.h
> +struct CfracParams {
Параметры для Cfrac алгоритма

2024-03-29 17:01 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +                          << factor_base.back()
Добавил assert строчкой выше

2024-03-29 17:04 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +      get_initial_brounker_sequence_items(n, sqrt_n);
Сделал итератор

2024-03-29 17:05 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +    total_candidates++;
Все же считаю что в самом итераторе такой флаг хранить некорректно -- он должен только ходить

В теории можно сделать обертку, но тут это избыточно думаю

2024-03-29 17:05 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +      if (factored_candidates % 100 == 0) {
Можно как параметр передать, пока не думаю что стоит того

2024-03-29 17:06 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +  return dixons_algorithm.find_factor();
Мы находим один, так что find_factor

2024-03-29 17:06 UTC, opukittpcenohhr commented on src/cfrac/find_factor_cfrac.cpp
> +                          << (double)factored_candidates /
Сделал static_cast

2024-03-29 17:06 UTC, opukittpcenohhr commented on src/cfrac/bhascara_brounker_sequence.h
> +
Спасибо за развернутый комментарий, сделал первый вариант

2024-03-29 17:07 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +  std::vector<boost::dynamic_bitset<>> a_;
Думаю, что этот будет сильно быстрее -- нам нужно чтобы быстро работал swap и ^=, а подход с "распрямленным" вектором не дает гарантий на асимптотику в таком случае

2024-03-29 17:09 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +void perform_gaussian_elimination(F2Matrix& matrix, size_t columns_to_perform);
Про порядок аргументов -- согласен, перенес 

Про pointer vs refernce -- понимаю, какие плюсы у указателя, но хочу тут принимать ссылку: название функции отражает, что будет меняться, ссылка не константная, так что довольно явно получается

2024-03-29 17:09 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.h
> +void perform_gaussian_elimination(F2Matrix& matrix, size_t columns_to_perform);
Переименовал, факты

2024-03-29 17:09 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.cpp
> +      std::swap(matrix[i], matrix[pivot]);
Выше описал, почему думаю что так будет быстрее

2024-03-29 17:10 UTC, opukittpcenohhr commented on src/dixons_algorithm/f2_matrix.cpp
> +    assert(matrix[i][i] == 1);
Нет, все так, был баг

Исправил

2024-03-29 17:10 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.h
> +      const bigint& n, const std::vector<size_t>& factor_base,
Принял span (будет точно копирование на создании вектора, но будет ровно одно)

2024-03-29 17:11 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.h
> +  void process_candidates(std::span<const bigint> candidates);
Ты прав

По сути, алгоритм Диксона это взять рандомные числа, и потом сделать машинерию с разложением по фактор-базе и гауссом

Сейчас я это разнес -- переименовал класс в FactorUsingCandidateCombination (возможно не лучшее название, но что придумал) и сделал метод find_factor_dixon с "обычной" сигнатурой

2024-03-29 17:12 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +bool DixonsAlgorithm::factorize_over_factor_base_and_fill_powers_matrix(
Сделал, действительно получилось лучше

2024-03-29 17:12 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +        auto g_r = mulmod<bigint>(
Не могу придумать как сделать тут красивее, так что оставлю так

2024-03-29 17:13 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +    if (auto factor = check_factor_candidate(i)) {
Переименовал меттод, по написанию -- вопрос привычки, мне наоброт кажется что очень удобно

2024-03-29 17:17 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +  }
Да, сделал тк

2024-03-29 17:18 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +    x = boost::multiprecision::sqrt(x);
Проблем нет, там assert в следующей строке на это

2024-03-29 17:19 UTC, opukittpcenohhr commented on src/dixons_algorithm/dixons_algorithm.cpp
> +  bool is_complete_square = true;
Факты, вынес

2024-03-29 17:20 UTC, opukittpcenohhr commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.h
> +bool is_fermat_pseudoprime_relative_to_base(const bigint& n, int base);
Да, ферма-псевдопростое -- это бинаиное свойство

2024-03-29 17:20 UTC, opukittpcenohhr commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.h
> +bool is_fermat_pseudoprime_relative_to_base(const bigint& n, int base);
Подход понял, согласен что так можно

Пока оставлю так

2024-03-29 17:21 UTC, opukittpcenohhr commented on src/fermat_pseudoprimality/fermat_pseudoprimality_test.cpp
> +    // for all relatively prime bases, and this is not the case
Добавил соседнюю функцию, которая проверяет не "математически псевдопростое или нет", а "простое или нет используя тест Ферма"

2024-03-29 17:21 UTC, opukittpcenohhr commented on src/legendre_symbol/legendre_symbol.cpp
> +int find_legendre_symbol(const bigint& n, const bigint& p) {
Я не смог найти

2024-03-29 17:22 UTC, opukittpcenohhr commented on src/legendre_symbol/legendre_symbol.cpp
> +  assert(p % 2 == 1);
Можно, но мне хватает и Лежандра

2024-03-29 17:23 UTC, opukittpcenohhr commented on src/legendre_symbol/legendre_symbol.cpp
> +  }
Переписал на тернарный оператор

2024-03-29 17:23 UTC, opukittpcenohhr commented on src/pollard_rho/pollard_rho_find_factor.cpp
> +    second_pointer = next_value(next_value(second_pointer));
Да, такое движение это по дизайну алгоритма

ИМХО и так хорошо выглядит, с итератором будет многословно

2024-03-29 17:25 UTC, opukittpcenohhr commented on src/pollard_rho/pollard_rho_find_factor.h
> +// n is known composite
Да

2024-03-29 17:25 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_congruence.h
> +std::vector<bigint> find_all_congruences(const bigint& n, const bigint& p);
Работает только когда p простое, да

Про вектор -- выбрал его как самый общий интерфейс

2024-03-29 17:25 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_factor_base.cpp
> +  std::vector<size_t> result{2};
Спасибо, исправил!

2024-03-29 17:26 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_factor_base.cpp
> +    if (is_prime[i]) {
Да, но тут перфоманс не очень болит -- эта часть работает очень быстро

2024-03-29 17:26 UTC, opukittpcenohhr commented on src/quadratic_sieve/find_factor_quadratic_sieve.h
> +    const bigint& n, const std::vector<size_t>& factor_base,
Это вообще должно быть в приватном интерфейсе, унес

2024-03-29 17:26 UTC, opukittpcenohhr commented on src/strong_pseudoprimality/strong_pseudoprimality_test.cpp
> +bool is_strong_pseudoprime(const bigint& n, std::span<const int> bases) {
Стараюсь везде в публичных использовать span

2024-03-29 17:27 UTC, opukittpcenohhr commented on src/trial_find_factor.cpp
> +  if (n % 2 == 0 && n > 2) {
Прописал precondition

2024-03-29 17:27 UTC, opukittpcenohhr commented on src/trial_primality_test.h
> +bool is_prime_trial(const bigint& x);
Сделал

2024-03-29 17:38 UTC, opukittpcenohhr commented
Добавил бенчмарки для QuadraticSieve и CFRAC, пофиксил комменты ко второму ревью (где мне казалось, что фиксить не стоит -- отписал, там в основном вопросы вкусов)

Больше ничего нового добавлять уже не буду: сделал все что планировал по проекту, возможно только добавлю какой-то график с распределением числа итераций у полларда-ро

2024-04-27 07:54 UTC, pipelinevp commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
yuemingming, @dec0dOS, @Amitmahato, @0xbhagi, @atakaly, @adham-elaraby, @MageyT, @SugamKuber, @nauqnew, @hisse, @Mapleshade20, @reny77, @yinxingyu, @Andy-wyx, @specmanic, @minhduc19990221, @cghiassi5, @m13poul, @eliyastein, @stalinMacias, @ConorH99, @JaredHightower, @rudraimmunefi, @sirap2305, @mohdamanmirza, @karbon0x, @karlop, @ctuong, @ankitsrivastava637, @nolimits-sagar, @npanium, @1024shao, @monomedio, @santoshtimilsina3, @alxivnov, @ScnuWang, @PalakKumari, @quantranld, @damaon, @caming34, @Huge, @crypto-hacker, @toby20130333, @JBMarfil, @FrensWagmi, @vanxindu, @xxibcill, @RozeenZorzis, @rego21, @DukeCaesar

2024-05-19 14:59 UTC, merged